# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
