# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('intro', models.TextField()),
                ('avatar', models.ImageField(upload_to='author_avatar/')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.RenameField(
            model_name='poetry',
            old_name='author',
            new_name='author_name',
        ),
    ]
