# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180320_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetry',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Author'),
            preserve_default=False,
        ),
    ]
