# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180322_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='cover',
            field=models.ImageField(upload_to='cover/%Y/%m/%d/'),
        ),
    ]
